title: Portfolio
description: Hi! I am Vaibhav Goel!
show_downloads: false

baseurl: "" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://a330w.github.io" # change this to the base hostname & protocol for your site

cayman-blog:
  date_format: "%b %-d, %Y"

remote_theme: lorepirri/cayman-blog

# social
author: a330w
image: 
twitter:
  username: 

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['about', 'projects', 'blog', 'contact']
