title: Portfolio
remote_theme: lorepirri/cayman-blog
show_downloads: true
    
# Navigation
navigation:
  - title: About
    url: /about
  - title: Projects
    url: /projects
  - title: Blog
    url: /blog
  - title: Contact
    url: /contact
    
